name: Deploy Vite React to Windows IIS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      # -------------------------------
      # WRITE SSH KEY TO FILE
      # -------------------------------
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # -------------------------------
      # TEST SSH CONNECTION
      # -------------------------------
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "echo CONNECTED"

      # -------------------------------
      # CLEAR IIS FOLDER
      # -------------------------------
      - name: Clear IIS folder
        run: |
          ssh -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
          "powershell -Command \"Remove-Item 'C:\inetpub\wwwroot\jagadesh.info\*' -Recurse -Force -ErrorAction SilentlyContinue\""

      # -------------------------------
      # COPY FILES TO IIS
      # -------------------------------
      - name: Upload files
        run: |
          scp -r -o StrictHostKeyChecking=no dist/* \
          ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/C:/inetpub/wwwroot/jagadesh.info
